### PR TITLE
RI-13 30 minute session timeout

### PR DESCRIPTION
**Pull request by dpoirier**
Applying this to all our own pages, but not
the admin (because apparently not all admin
pages load jQuery and it doesn't seem worth
fixing, given that we do not plan to expose
the admin to anyone but us).

I've added an empty page at / just so we can
test this. To test:

* Set short times in your local.py:

    # django-session-security
    SESSION_SECURITY_WARN_AFTER = 30  # seconds
    SESSION_SECURITY_EXPIRE_AFTER = 60

* Go to /admin and login
* Go to /
* Wait 30 seconds without touching anything and there should
  be a warning that the session will time out soon.
* Wait 30 more seconds and it should time out.
* Go to /admin and verify you need to login again. Login.
* Go to /
* Wait 30 seconds for the warning.
* Click in the page or move the mouse or something.
* Wait 30 more seconds and the login should not time out.

https://caktus.atlassian.net/browse/RI-13

### CODE REVIEW

**Comment by vkurup** [comment]
When trying to load '/', I get: 

```
UncompressableFileError at /
'libs/modernizr.js' could not be found in the COMPRESS_ROOT '/home/vkurup/dev/rescue_id/public/static' or with staticfiles.
```

I then ran `make update-static-libs` and it worked. Do those static files need to be added to this PR?

:+1: afterwards

**Comment by dpoirier** [comment]
I hit the same thing.  I think running 'make update-static-libs' is just another thing we'll have to get used to doing.

**Comment by vkurup** [comment]
But, wouldn't we just do it once, and then commit those files to the project?

**Comment by dpoirier** [comment]
I thought the idea was not to be checking static files from other projects into our repos.

**Comment by vkurup** [comment]
:hourglass:

**Pull request merged**
